name: Deploy to GKE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Inject Grafana password
      run: |
        sed -i "s/\${GRAFANA_PASSWORD}/${{ secrets.GRAFANA_PASSWORD }}/g" helm/values.yaml
    
    - name: Terraform Init & Apply
      working-directory: terraform
      run: |
        terraform init
        terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}"

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials gke-monitoring-cluster --region europe-west1 --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Helm chart
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install monitoring prometheus-community/kube-prometheus-stack -f helm/values.yaml --namespace monitoring --create-namespace
